// mobile-app/src/types/ai.ts
/* =====================================================
    AI CHAT
===================================================== */

export interface AIChatRequest {
  user_id: number;
  question: string;
}

export interface AIChatResponse {
  /** Human readable answer from AI */
  answer: string;

  /** SQL generated by the AI (for debug / transparency) */
  sql_used?: string;

  /** Raw rows returned by DB */
  rows?: Array<Record<string, any>>;
}

/* =====================================================
    AI INSIGHTS  (Phase 2 / Future)
===================================================== */

export type AIInsightSeverity = "low" | "medium" | "high";

export interface AIInsight {
  title: string;
  severity: AIInsightSeverity;
  message: string;
}

/* =====================================================
    AI AUTO CATEGORIZATION
===================================================== */

export interface AICategorizeRequest {
  description: string;
}

export interface AICategorizeResponse {
  category_id: number;
  confidence: number;   // 0 → 1
}
