// mobile-app/src/types/ai.ts
/* =====================================================
    AI CHAT
===================================================== */

export interface AIChatRequest {
  user_id: number;
  question: string;
}

export interface AIChatResponse {
  /** Human readable answer from AI */
  answer: string;

  /** SQL generated by the AI (for debug / transparency) */
  sql_used?: string;

  /** Raw rows returned by DB */
  rows?: Array<Record<string, any>>;
}

/* =====================================================
    AI INSIGHTS  
===================================================== */

export type AIInsightSeverity = "LOW" | "MEDIUM" | "HIGH";

export type AIInsightType =
  | "SUMMARY"
  | "BUDGET_STATUS"
  | "BUDGET_FORECAST"
  | "ANOMALY";

export interface AIInsight {
  /** DB id (optional for non-persisted insights) */
  id?: number;

  /** Type of insight */
  insight_type: AIInsightType;

  /** Short title shown in card header */
  title: string;

  /** Main message shown to the user */
  message: string;

  /** Severity level used for coloring & priority */
  severity: AIInsightSeverity;

  /** Related category (if applicable) */
  category_id?: number;

  /** Extra metadata (explanation, forecast values, etc.) */
  metadata?: {
    why?: string;
    [key: string]: any;
  };

  /** Confidence score (0–1) */
  confidence?: number;

  /** When insight was generated */
  created_at?: string;
}


/* =====================================================
    AI AUTO CATEGORIZATION
===================================================== */

export interface AICategorizeRequest {
  description: string;
}

export interface AICategorizeResponse {
  category_id: number;
  confidence: number;   // 0 → 1
}

export interface AIVoiceChatResponse {
  voice_text: string;    // transcription
  ai_answer: string;     // final answer
  sql_used?: string | null; // optional debug
  rows?: any[]; // optional debug rows
}