export const DRAWER_ITEMS = [
  { name: '(dashboard)', title: 'Dashboard', icon: 'house.fill' }, 
  { name: '(category)', title: 'Category', icon: 'cart.fill' },
	{ name: '(account)', title: 'Account', icon: 'person.crop.circle' },
  { name: '(budget)', title: 'Budget', icon: 'wallet.pass.fill' }, 
	{ name: '(category)', title: 'Category', icon: 'tag.fill' },
  { name: '(expense)', title: 'Expense', icon: 'creditcard.fill' },
  { name: '(analytics)', title: 'Analytics', icon: 'chart.bar.fill' },
  { name: '(reports)', title: 'Reports', icon: 'folder.fill' },
  { name: '(help)', title: 'Help', icon: 'questionmark.circle.fill' },
  { name: '(feedback)', title: 'Feedback', icon: 'envelope.badge.fill' },
  { name: '(settings)', title: 'Settings', icon: 'gearshape.fill' },
  { name: '(about)', title: 'About', icon: 'info.circle.fill' },
  { name: 'logout', title: 'Logout', icon: 'rectangle.portrait.and.arrow.right.fill' },
];